### ISSUE TITLE
Build error: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by pvtodorov** [skieffer/adapaca#2]
When I try to compile on macOS I get the following error:
```
Undefined symbols for architecture x86_64:
  "topology::assertNoSegmentRectIntersection(std::__1::vector<topology::Node*, std::__1::allocator<topology::Node*> > const&, std::__1::vector<topology::Edge*, std::__1::allocator<topology::Edge*> > const&)", referenced from:
      makeFeasible(std::__1::vector<vpsc::Rectangle*, std::__1::allocator<vpsc::Rectangle*> >&, std::__1::vector<std::__1::pair<unsigned int, unsigned int>, std::__1::allocator<std::__1::pair<unsigned int, unsigned int> > >&, std::__1::vector<topology::Edge*, std::__1::allocator<topology::Edge*> >&, std::__1::vector<topology::Node*, std::__1::allocator<topology::Node*> >&, double) in beautify.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [beautify] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

My system information
```
Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
```

```
macOS Sierra
System Version:	macOS 10.12.4 (16E195)
Kernel Version:	Darwin 16.5.0
```

**Comment by skieffer** [comment]
Hi, sorry for the delay. I would like to help but am usually at a loss when it comes to compiler and build errors. (Not my department on this particular project.) From the error message you posted I'm not able to figure out the problem, unfortunately.

I can tell you that I just tried cloning a fresh copy of the repo and building from scratch and it went fine. Some info about my system:

```
$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```

```
OS X El Capitan
Version 10.11.6

Darwin Kernel Version 15.6.0
```

I hope you can figure it out. In the meantime I have a question for you: We have talked about setting up a server where people can upload graphs and download a HOLA layout. Would you be iterested in using that? Would that likely suffice for the experiments you wish to run? What file formats would you want to use?

**Comment by pvtodorov** [comment]
Thanks for the reply (rather quick, considering I posted over the weekend!) I will see if I can use the information provided to resolve my issue.

**It would be great to be able to try this out using a webservice.** Ultimately, I was planning on setting up my own in order to communicate with cytoscape.js for initial layout of a biological networks. I planned on communicating with HOLA using the GML format, but ultimately I will translate that to a format that I can use with cytoscape.js.

**Comment by skieffer** [comment]
Hi. Took a while to find time for it, but here is [a simple "test drive" page for HOLA](http://graphlayout.net/HOLA/testdrive). We're not ready to host a full-on web service with slick API just yet, but this GUI should be good enough for trying out a few layouts by hand.
